### ISSUE TITLE
Theme color names

### ISSUE THREAD

**Issue by nzoschke** [Kalos-Creative-Group/grax-platform-tailwind#2]
The theme introduces preferred colors like `gray-extra-dark`, `gray-medium`, `gray-extra-extra-light`.

These are added to the stock `text-gray-500` colors.

Instead of adding new color names, can the theme replace the `text-gray-500` style ones with preferred shades of gray?

That would also help us copy paste pre-existing components like this page header and not have to rework the colors all the time.

https://tailwindui.com/components/application-ui/headings/page-headings#component-7654075f650c9f1044bfcf1b1b6ffd77

<img width="434" alt="Screenshot 2023-05-04 at 11 28 35 AM" src="https://user-images.githubusercontent.com/147410/236295905-130b2012-52fc-4473-a9b1-d96ffa3b55c1.png">

**Comment by alex-kcg** [comment]
Hey @nzoschke - I've updated the Tailwind config and the markup for the components in this project to use that convention.  I replicated the changes across to the codebase for the WordPress theme as well, so moving forward we'll be able to share more code for components between those sites when needed.

While it is possible to omit the default values for the Tailwind color palette, I think we're better off not doing so because it would potentially cause components that you pull from Tailwind UI not to display properly if they rely on those classes.  Instead, I've re-mapped all of the existing palettes to our custom colors wherever possible in case you need to pull something off the shelf that we don't have time to customize.

I also updated our platform "style-guide" page with a new colors section that shows the most important colors to pick from to match the branding of grax.com  There are many other colors inbetween if we need a variant, but those are the important ones to use wherever possible:

https://grax-platform-tailwind.netlify.app/
